# Generated by Django 2.2.4 on 2021-12-17 09:59

import django.core.validators
from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211217_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, '너무 짧군요! 10자 이상 적어주세요'), posts.validators.validate_symbols]),
        ),
    ]
